example/example/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('pyfb_normalization.urls', namespace='pyfb-normalization')),
]

pyfb_normalization/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views


app_name = 'pyfb_normalization'

router = routers.DefaultRouter()
router.register(r'callmappingrule', api.CallMappingRuleViewSet)
router.register(r'normalizationgrp', api.NormalizationGrpViewSet)
router.register(r'normalizationrule', api.NormalizationRuleViewSet)
router.register(r'normalizationrulegrp', api.NormalizationRuleGrpViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    path('api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for CallMappingRule
    path('pyfb_normalization/callmappingrule/', views.CallMappingRuleListView.as_view(), name='pyfb_normalization_callmappingrule_list'),
    path('pyfb_normalization/callmappingrule/create/', views.CallMappingRuleCreateView.as_view(), name='pyfb_normalization_callmappingrule_create'),
    path('pyfb_normalization/callmappingrule/detail/<int:pk>/', views.CallMappingRuleDetailView.as_view(), name='pyfb_normalization_callmappingrule_detail'),
    path('pyfb_normalization/callmappingrule/update/<int:pk>/', views.CallMappingRuleUpdateView.as_view(), name='pyfb_normalization_callmappingrule_update'),
)

urlpatterns += (
    # urls for NormalizationGrp
    path('pyfb_normalization/normalizationgrp/', views.NormalizationGrpListView.as_view(), name='pyfb_normalization_normalizationgrp_list'),
    path('pyfb_normalization/normalizationgrp/create/', views.NormalizationGrpCreateView.as_view(), name='pyfb_normalization_normalizationgrp_create'),
    path('pyfb_normalization/normalizationgrp/detail/<int:pk>/', views.NormalizationGrpDetailView.as_view(), name='pyfb_normalization_normalizationgrp_detail'),
    path('pyfb_normalization/normalizationgrp/update/<int:pk>/', views.NormalizationGrpUpdateView.as_view(), name='pyfb_normalization_normalizationgrp_update'),
)

urlpatterns += (
    # urls for NormalizationRule
    path('pyfb_normalization/normalizationrule/', views.NormalizationRuleListView.as_view(), name='pyfb_normalization_normalizationrule_list'),
    path('pyfb_normalization/normalizationrule/create/', views.NormalizationRuleCreateView.as_view(), name='pyfb_normalization_normalizationrule_create'),
    path('pyfb_normalization/normalizationrule/detail/<int:pk>/', views.NormalizationRuleDetailView.as_view(), name='pyfb_normalization_normalizationrule_detail'),
    path('pyfb_normalization/normalizationrule/update/<int:pk>/', views.NormalizationRuleUpdateView.as_view(), name='pyfb_normalization_normalizationrule_update'),
)

urlpatterns += (
    # urls for NormalizationRuleGrp
    path('pyfb_normalization/normalizationrulegrp/', views.NormalizationRuleGrpListView.as_view(), name='pyfb_normalization_normalizationrulegrp_list'),
    path('pyfb_normalization/normalizationrulegrp/create/', views.NormalizationRuleGrpCreateView.as_view(), name='pyfb_normalization_normalizationrulegrp_create'),
    path('pyfb_normalization/normalizationrulegrp/detail/<int:pk>/', views.NormalizationRuleGrpDetailView.as_view(), name='pyfb_normalization_normalizationrulegrp_detail'),
    path('pyfb_normalization/normalizationrulegrp/update/<int:pk>/', views.NormalizationRuleGrpUpdateView.as_view(), name='pyfb_normalization_normalizationrulegrp_update'),
)

pyfb_normalization/models.py
# -*- coding: utf-8 -*-
from django.urls import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from model_utils.models import TimeStampedModel


class NormalizationGrp(TimeStampedModel):
    """Normalization group table"""
    name = models.CharField(
        _(u'Rule Group name'),
        max_length=30)
    description = models.TextField(
        _(u'description'),
        blank=True)

    class Meta:
        db_table = 'pyfb_normalization_grp'
        ordering = ('name',)
        verbose_name = _(u'Normalization Group')
        verbose_name_plural = _(u'Normalization Groups')

    def __str__(self):
        return u'%s' % self.name

    def __unicode__(self):
        return u"%s" % (self.name)

    def get_absolute_url(self):
        return reverse('pyfb-normalization:pyfb_normalization_normalizationgrp_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('pyfb-normalization:pyfb_normalization_normalizationgrp_update', args=(self.pk,))


class NormalizationRule(TimeStampedModel):
    """ Normalization rules table """
    name = models.CharField(
        _(u'rule title'),
        max_length=30)
    DEFAULT_MATCH = (
        (0, _(u'Equal')),
        (1, _(u'Regex')),
    )
    match_op = models.IntegerField(
        _(u'Type of match (equal or regex)'),
        choices=DEFAULT_MATCH,
        default=1)
    match_exp = models.CharField(
        _(u"match expression"),
        blank=True,
        default='',
        max_length=64,
        help_text=_(u"""Example : ^(33)[0-9].*"""))
    match_len = models.IntegerField(
        _(u'match length'),
        default=0)
    subst_exp = models.CharField(
        _(u"substitution expression"),
        blank=True,
        default='',
        max_length=64,
        help_text=_(u"""Example : ^(33)([0-9].*)"""))
    repl_exp = models.CharField(
        _(u"replacement expression"),
        blank=True,
        default='',
        max_length=64,
        help_text=_(u"""Example : 0033\1"""))
    DEFAULT_CALL = (
        ("", _(u'N/A')),
    )
    attrs = models.CharField(
        _(u"attributes"),
        blank=True,
        choices=DEFAULT_CALL,
        default='',
        max_length=64,
        help_text=_(u"""Rule to map specific route -
            Default set to nothing : N/A - not used"""))
    description = models.TextField(
        _(u'description'),
        blank=True)

    class Meta:
        db_table = 'pyfb_normalization_rule'
        ordering = ('name', 'match_exp')
        verbose_name = _(u'Normalization Rule')
        verbose_name_plural = _(u'Normalization Rules')

    def __str__(self):
        return u"%s (%s:%s)" % (self.name, self.match_op, self.match_exp)

    def __unicode__(self):
        return u"%s (%s:%s)" % (self.name, self.match_op, self.match_exp)

    def get_absolute_url(self):
        return reverse('pyfb-normalization:pyfb_normalization_normalizationrule_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('pyfb-normalization:pyfb_normalization_normalizationrule_update', args=(self.pk,))


class NormalizationRuleGrp(TimeStampedModel):
    """ Normalization rules group table """
    pr = models.IntegerField(
        _(u'priority'),
        help_text=_(u"""Rule order"""))
    description = models.TextField(
        _(u'description'),
        blank=True)

    # Relationship Fields
    dpid = models.ForeignKey(
        'pyfb_normalization.NormalizationGrp',
        on_delete=models.PROTECT,
        related_name="normalizationgrps",
        verbose_name=_(u"Normalization Group")
    )
    rule = models.ForeignKey(
        'pyfb_normalization.NormalizationRule',
        on_delete=models.PROTECT,
        related_name="normalizationrules",
        verbose_name=_(u"Normalization Rule")
    )

    class Meta:
        db_table = 'pyfb_normalization_rule_grp'
        ordering = ('dpid', 'pr')
        unique_together = (("dpid", "pr"),)
        verbose_name = _(u'Normalization Rule-Group')
        verbose_name_plural = _(u'Normalization Rules-Groups')

    def __str__(self):
        return u"%s - Priority: %s Rule: %s" % (self.dpid,
                                                self.pr,
                                                self.rule)

    def __unicode__(self):
        return u"%s - Priority: %s Rule: %s" % (self.dpid,
                                                self.pr,
                                                self.rule)

    def get_absolute_url(self):
        return reverse('pyfb-normalization:pyfb_normalization_normalizationrulegrp_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('pyfb-normalization:pyfb_normalization_normalizationrulegrp_update', args=(self.pk,))


class CallMappingRule(TimeStampedModel):
    """ Normalization call mapping rules table """
    name = models.CharField(
        _(u'rule title'),
        max_length=30)
    dpid = models.IntegerField(
        _(u'Dialplan id'),
        default=0,
        help_text=_(u"""Need to be 0, instead of the rule
            will not be used"""))
    pr = models.IntegerField(
        _(u'Priority rule'),
        unique=True,
        help_text=_(u"""Priority of rule"""))

    DEFAULT_MATCH = (
        (0, _(u'Equal')),
        (1, _(u'Regex')),
    )
    match_op = models.IntegerField(
        _(u'Type of match (equal or regex)'),
        choices=DEFAULT_MATCH,
        default=1)
    match_exp = models.CharField(
        _(u"match expression"),
        blank=True,
        default='',
        max_length=64,
        help_text=_(u"""Example : ^(33)[0-9].*"""))
    match_len = models.IntegerField(
        _(u'match length'),
        default=0)
    subst_exp = models.CharField(
        _(u"subst prefix"),
        blank=True,
        default='',
        max_length=64,
        help_text=_(u"""Example : ^(33)([0-9].*)"""))
    repl_exp = models.CharField(
        _(u"replacement prefix"),
        blank=True,
        default='',
        max_length=64,
        help_text=_(u"""Example : 0033\1"""))
    DEFAULT_CALL = (
        ("", _(u'N/A')),
        ("PSTN", _(u'PSTN')),
        ("EMERGENCY", _(u'EMERGENCY NUMBER')),
        ("OWN", _(u'OWN NUMBERS')),
        ("SPEEDDIAL", _(u'SPEED DIAL')),
        ("DROP", _(u'DROP NUMBERS')),
    )
    attrs = models.CharField(
        _(u"attributes"),
        blank=True,
        choices=DEFAULT_CALL,
        default='',
        max_length=64,
        help_text=_(u"""Rule to map specific route -
            Default set to nothing : N/A"""))
    description = models.TextField(
        _(u'description'),
        blank=True)

    class Meta:
        db_table = 'pyfb_call_mapping_rule'
        ordering = ('pr',)
        unique_together = (("dpid", "pr"),)
        verbose_name = _(u'Call Mapping Rule')
        verbose_name_plural = _(u'Call Mapping Rules')

    def __str__(self):
        return u"%s- %s %s (%s/%s) %s" % (
            self.id,
            self.name,
            self.pr,
            self.match_op,
            self.match_exp,
            self.attrs)

    def __unicode__(self):
        return u"%s- %s %s (%s/%s) %s" % (
            self.id,
            self.name,
            self.pr,
            self.match_op,
            self.match_exp,
            self.attrs)

    def get_absolute_url(self):
        return reverse('pyfb-normalization:pyfb_normalization_callmappingrule_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('pyfb-normalization:pyfb_normalization_callmappingrule_update', args=(self.pk,))

pyfb_normalization/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import CallMappingRule, NormalizationGrp, NormalizationRule, NormalizationRuleGrp


class CallMappingRuleForm(forms.ModelForm):
    class Meta:
        model = CallMappingRule
        fields = ['name', 'dpid', 'pr', 'match_op', 'match_exp', 'match_len', 'subst_exp', 'repl_exp', 'attrs', 'description']


class NormalizationGrpForm(forms.ModelForm):
    class Meta:
        model = NormalizationGrp
        fields = ['name', 'description']


class NormalizationRuleForm(forms.ModelForm):
    class Meta:
        model = NormalizationRule
        fields = ['name', 'match_op', 'match_exp', 'match_len', 'subst_exp', 'repl_exp', 'attrs', 'description']


class NormalizationRuleGrpForm(forms.ModelForm):
    class Meta:
        model = NormalizationRuleGrp
        fields = ['pr', 'description', 'dpid', 'rule']

pyfb_normalization/views.py
# -*- coding: utf-8 -*-
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .models import CallMappingRule, NormalizationGrp, NormalizationRule, NormalizationRuleGrp
from .forms import CallMappingRuleForm, NormalizationGrpForm, NormalizationRuleForm, NormalizationRuleGrpForm


class CallMappingRuleListView(ListView):
    model = CallMappingRule


class CallMappingRuleCreateView(CreateView):
    model = CallMappingRule
    form_class = CallMappingRuleForm


class CallMappingRuleDetailView(DetailView):
    model = CallMappingRule


class CallMappingRuleUpdateView(UpdateView):
    model = CallMappingRule
    form_class = CallMappingRuleForm


class NormalizationGrpListView(ListView):
    model = NormalizationGrp


class NormalizationGrpCreateView(CreateView):
    model = NormalizationGrp
    form_class = NormalizationGrpForm


class NormalizationGrpDetailView(DetailView):
    model = NormalizationGrp


class NormalizationGrpUpdateView(UpdateView):
    model = NormalizationGrp
    form_class = NormalizationGrpForm


class NormalizationRuleListView(ListView):
    model = NormalizationRule


class NormalizationRuleCreateView(CreateView):
    model = NormalizationRule
    form_class = NormalizationRuleForm


class NormalizationRuleDetailView(DetailView):
    model = NormalizationRule


class NormalizationRuleUpdateView(UpdateView):
    model = NormalizationRule
    form_class = NormalizationRuleForm


class NormalizationRuleGrpListView(ListView):
    model = NormalizationRuleGrp


class NormalizationRuleGrpCreateView(CreateView):
    model = NormalizationRuleGrp
    form_class = NormalizationRuleGrpForm


class NormalizationRuleGrpDetailView(DetailView):
    model = NormalizationRuleGrp


class NormalizationRuleGrpUpdateView(UpdateView):
    model = NormalizationRuleGrp
    form_class = NormalizationRuleGrpForm

pyfb_normalization/templates/pyfb_normalization/callmappingrule_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-normalization:pyfb_normalization_callmappingrule_list' %}">{% trans "call mapping rule listing" %}</a></p>
<table class="table">
<tr><td>{% trans "name" %}</td><td>{{ object.name }}</td></tr>
<tr><td>dpid</td><td>{{ object.dpid }}</td></tr>
<tr><td>pr</td><td>{{ object.pr }}</td></tr>
<tr><td>match_op</td><td>{{ object.match_op }}</td></tr>
<tr><td>match_exp</td><td>{{ object.match_exp }}</td></tr>
<tr><td>match_len</td><td>{{ object.match_len }}</td></tr>
<tr><td>subst_exp</td><td>{{ object.subst_exp }}</td></tr>
<tr><td>repl_exp</td><td>{{ object.repl_exp }}</td></tr>
<tr><td>attrs</td><td>{{ object.attrs }}</td></tr>
<tr><td>{% trans "description" %}</td><td>{{ object.description }}</td></tr>
<tr><td>{% trans "created" %}</td><td>{{ object.created }}</td></tr>
<tr><td>{% trans "modified" %}</td><td>{{ object.modified }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">{% trans "edit call mapping rule" %}</a>

{% endblock %}

pyfb_normalization/templates/pyfb_normalization/callmappingrule_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-normalization:pyfb_normalization_callmappingrule_list' %}">{% trans "call mapping rule listing" %}</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">{% trans "submit" %}</button>
</form>
{% endblock %}

pyfb_normalization/templates/pyfb_normalization/callmappingrule_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-normalization:pyfb_normalization_callmappingrule_list' %}">{% trans "call mapping rule listing" %}</a></p>
<table class="table">
<tr>
<td>ID</td><td>{% trans "Link" %}</td>
    <td>{% trans "name" %}</td>
    <td>dpid</td>
    <td>pr</td>
    <td>match_op</td>
    <td>match_exp</td>
    <td>match_len</td>
    <td>subst_exp</td>
    <td>repl_exp</td>
    <td>attrs</td>
    <td>{% trans "description" %}</td>
    <td>{% trans "created" %}</td>
    <td>{% trans "modified" %}</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.name }}</td>
    <td>{{ object.dpid }}</td>
    <td>{{ object.pr }}</td>
    <td>{{ object.match_op }}</td>
    <td>{{ object.match_exp }}</td>
    <td>{{ object.match_len }}</td>
    <td>{{ object.subst_exp }}</td>
    <td>{{ object.repl_exp }}</td>
    <td>{{ object.attrs }}</td>
    <td>{{ object.description }}</td>
    <td>{{ object.created }}</td>
    <td>{{ object.modified }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-normalization:pyfb_normalization_callmappingrule_create' %}">{% trans "create new call mapping rule" %}</a>
{% endblock %}

pyfb_normalization/templates/pyfb_normalization/normalizationgrp_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-normalization:pyfb_normalization_normalizationgrp_list' %}">{% trans "normalization group listing" %}</a></p>
<table class="table">
<tr><td>{% trans "name" %}</td><td>{{ object.name }}</td></tr>
<tr><td>{% trans "description" %}</td><td>{{ object.description }}</td></tr>
<tr><td>{% trans "created" %}</td><td>{{ object.created }}</td></tr>
<tr><td>{% trans "modified" %}</td><td>{{ object.modified }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">{% trans "edit normalization group" %}</a>

{% endblock %}

pyfb_normalization/templates/pyfb_normalization/normalizationgrp_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-normalization:pyfb_normalization_normalizationgrp_list' %}">{% trans "normalization group listing" %}</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">{% trans "submit" %}</button>
</form>
{% endblock %}

pyfb_normalization/templates/pyfb_normalization/normalizationgrp_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-normalization:pyfb_normalization_normalizationgrp_list' %}">{% trans "normalization group listing" %}</a></p>
<table class="table">
<tr>
<td>ID</td><td>{% trans "Link" %}</td>
    <td>{% trans "name" %}</td>
    <td>{% trans "description" %}</td>
    <td>{% trans "created" %}</td>
    <td>{% trans "modified" %}</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.name }}</td>
    <td>{{ object.description }}</td>
    <td>{{ object.created }}</td>
    <td>{{ object.modified }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-normalization:pyfb_normalization_normalizationgrp_create' %}">{% trans "create new normalization group" %}</a>
{% endblock %}

pyfb_normalization/templates/pyfb_normalization/normalizationrule_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-normalization:pyfb_normalization_normalizationrule_list' %}">{% trans "normalization rule listing" %}</a></p>
<table class="table">
<tr><td>{% trans "name" %}</td><td>{{ object.name }}</td></tr>
<tr><td>match_op</td><td>{{ object.match_op }}</td></tr>
<tr><td>match_exp</td><td>{{ object.match_exp }}</td></tr>
<tr><td>match_len</td><td>{{ object.match_len }}</td></tr>
<tr><td>subst_exp</td><td>{{ object.subst_exp }}</td></tr>
<tr><td>repl_exp</td><td>{{ object.repl_exp }}</td></tr>
<tr><td>attrs</td><td>{{ object.attrs }}</td></tr>
<tr><td>{% trans "description" %}</td><td>{{ object.description }}</td></tr>
<tr><td>{% trans "created" %}</td><td>{{ object.created }}</td></tr>
<tr><td>{% trans "modified" %}</td><td>{{ object.modified }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">{% trans "edit normalization rule" %}</a>

{% endblock %}

pyfb_normalization/templates/pyfb_normalization/normalizationrule_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-normalization:pyfb_normalization_normalizationrule_list' %}">{% trans "normalization rule listing" %}</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">{% trans "submit" %}</button>
</form>
{% endblock %}

pyfb_normalization/templates/pyfb_normalization/normalizationrule_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-normalization:pyfb_normalization_normalizationrule_list' %}">{% trans "normalization rule listing" %}</a></p>
<table class="table">
<tr>
<td>ID</td><td>{% trans "Link" %}</td>
    <td>{% trans "name" %}</td>
    <td>match_op</td>
    <td>match_exp</td>
    <td>match_len</td>
    <td>subst_exp</td>
    <td>repl_exp</td>
    <td>attrs</td>
    <td>{% trans "description" %}</td>
    <td>{% trans "created" %}</td>
    <td>{% trans "modified" %}</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.name }}</td>
    <td>{{ object.match_op }}</td>
    <td>{{ object.match_exp }}</td>
    <td>{{ object.match_len }}</td>
    <td>{{ object.subst_exp }}</td>
    <td>{{ object.repl_exp }}</td>
    <td>{{ object.attrs }}</td>
    <td>{{ object.description }}</td>
    <td>{{ object.created }}</td>
    <td>{{ object.modified }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-normalization:pyfb_normalization_normalizationrule_create' %}">{% trans "create new normalization rule" %}</a>
{% endblock %}

pyfb_normalization/templates/pyfb_normalization/normalizationrulegrp_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-normalization:pyfb_normalization_normalizationrulegrp_list' %}">{% trans "normalization rule group Listing" %}</a></p>
<table class="table">
<tr><td>pr</td><td>{{ object.pr }}</td></tr>
<tr><td>{% trans "description" %}</td><td>{{ object.description }}</td></tr>
<tr><td>{% trans "created" %}</td><td>{{ object.created }}</td></tr>
<tr><td>{% trans "modified" %}</td><td>{{ object.modified }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">{% trans "edit normalization rule group" %}</a>

{% endblock %}

pyfb_normalization/templates/pyfb_normalization/normalizationrulegrp_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-normalization:pyfb_normalization_normalizationrulegrp_list' %}">{% trans "normalization rule group listing" %}</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">{% trans "submit" %}</button>
</form>
{% endblock %}

pyfb_normalization/templates/pyfb_normalization/normalizationrulegrp_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-normalization:pyfb_normalization_normalizationrulegrp_list' %}">{% trans "normalization rule group listing" %}</a></p>
<table class="table">
<tr>
<td>ID</td><td>{% trans "Link" %}</td>
    <td>pr</td>
    <td>{% trans "description" %}</td>
    <td>{% trans "created" %}</td>
    <td>{% trans "modified" %}</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.pr }}</td>
    <td>{{ object.description }}</td>
    <td>{{ object.created }}</td>
    <td>{{ object.modified }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-normalization:pyfb_normalization_normalizationrulegrp_create' %}">{% trans "create new normalization rule group" %}</a>
{% endblock %}